-- S7 Mentorship: all 13 migrations, 0001_monetization.sql to 0013_lesson_submissions.sql, in order.
-- Generated by scripts/bundle-migrations.mjs (npm run db:bundle); do not edit by hand.
-- Copy ALL of it — it is long — into Supabase → SQL Editor → Run.
-- One transaction: if any statement fails, nothing is changed.

begin;

-- ========================================================================================
-- 0001_monetization.sql
-- ========================================================================================

-- Monetization schema for S7 Robotics Platform.
--
-- The app was local-first: every user, lesson and submission lived in one localStorage key.
-- That is fine for progress and XP, which nobody gains by forging. It is not fine for money.
-- Anything that decides whether a student may open paid content, or whether an adult may
-- teach on the platform, lives here instead — where the browser can read but never write.
--
-- The rule this file enforces throughout: the client may cache a decision, never make one.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------
-- Mirrors the client's User type minus the password. Auth owns credentials now;
-- the old model kept them in cleartext in the browser, which must not survive this change.

do $$ begin create type user_role as enum ('student', 'mentor'); exception when duplicate_object then null; end $$;

create table if not exists profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  name          text not null,
  role          user_role not null default 'student',
  avatar        text not null default '',
  title         text,
  bio           text,
  city          text,
  -- Admin is set by a database operator, never by anything the client can post.
  is_admin      boolean not null default false,
  joined_at     timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- mentor_applications  (replaces the shared admin PIN)
-- ---------------------------------------------------------------------------
-- A PIN is one secret shared by everyone who has ever been a mentor: it cannot be revoked
-- for one person, and it says nothing about who is behind the keyboard. An application is
-- reviewed once, per person, and can be withdrawn.
--
-- The document columns hold Storage object paths, never file bytes and never URLs.

do $$ begin create type application_status as enum ('pending', 'approved', 'rejected'); exception when duplicate_object then null; end $$;

create table if not exists mentor_applications (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references profiles (id) on delete cascade,
  status              application_status not null default 'pending',
  legal_name          text not null,
  bio                 text not null,
  credential_doc_path text,
  id_doc_path         text,
  submitted_at        timestamptz not null default now(),
  reviewed_at         timestamptz,
  reviewer_id         uuid references profiles (id),
  rejection_reason    text
);

-- One live application per person. A rejected one may be replaced; a pending or approved
-- one may not be duplicated to get a second reviewer's opinion.
create unique index if not exists mentor_applications_one_live
  on mentor_applications (user_id)
  where status in ('pending', 'approved');

-- ---------------------------------------------------------------------------
-- mentor_accounts  (Stripe Connect)
-- ---------------------------------------------------------------------------
-- charges_enabled is Stripe's answer, cached. It is refreshed from the API rather than
-- trusted from a client, because it gates whether a lesson may be sold at all.

create table if not exists mentor_accounts (
  user_id           uuid primary key references profiles (id) on delete cascade,
  stripe_account_id text not null unique,
  charges_enabled   boolean not null default false,
  payouts_enabled   boolean not null default false,
  updated_at        timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- custom_lessons
-- ---------------------------------------------------------------------------
-- Money is integer minor units throughout. Floats do not represent 0.1 exactly, and a
-- rounding drift in a fee calculation is somebody's missing cent.

create table if not exists custom_lessons (
  id            uuid primary key default gen_random_uuid(),
  author_id     uuid not null references profiles (id) on delete cascade,
  title         text not null,
  summary       text not null,
  -- Storage path in the private lesson-materials bucket. The old build inlined the whole
  -- file as a data: URL in client state, which hands a paid PDF to anyone who looks.
  material_path text,
  material_name text,
  material_mime text,
  material_size integer,
  price_cents   integer not null default 0 check (price_cents >= 0 and price_cents <= 100000000),
  currency      text not null default 'usd' check (char_length(currency) = 3),
  published     boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists custom_lessons_author on custom_lessons (author_id);
create index if not exists custom_lessons_published on custom_lessons (published) where published;

-- ---------------------------------------------------------------------------
-- custom_tasks
-- ---------------------------------------------------------------------------
-- answer_index is the answer key. It is server-only: no student-facing query selects it,
-- and RLS below never exposes this table to a student directly.

do $$ begin create type task_kind as enum ('quiz', 'code', 'open'); exception when duplicate_object then null; end $$;

create table if not exists custom_tasks (
  id           uuid primary key default gen_random_uuid(),
  lesson_id    uuid not null references custom_lessons (id) on delete cascade,
  position     integer not null,
  kind         task_kind not null,
  prompt       text not null,
  points       integer not null default 0 check (points >= 0 and points <= 100),
  options      jsonb,
  answer_index integer,
  starter      text
);

create index if not exists custom_tasks_lesson on custom_tasks (lesson_id, position);

-- ---------------------------------------------------------------------------
-- orders / entitlements
-- ---------------------------------------------------------------------------
-- stripe_session_id is unique so a webhook redelivery — which Stripe does on purpose —
-- collides instead of granting a second entitlement or double-counting revenue.

do $$ begin create type order_status as enum ('pending', 'paid', 'failed', 'refunded'); exception when duplicate_object then null; end $$;

create table if not exists orders (
  id                 uuid primary key default gen_random_uuid(),
  stripe_session_id  text not null unique,
  stripe_payment_intent text,
  student_id         uuid not null references profiles (id) on delete cascade,
  lesson_id          uuid not null references custom_lessons (id) on delete restrict,
  amount_cents       integer not null check (amount_cents >= 0),
  platform_fee_cents integer not null check (platform_fee_cents >= 0),
  currency           text not null,
  status             order_status not null default 'pending',
  created_at         timestamptz not null default now(),
  paid_at            timestamptz,
  constraint fee_not_above_amount check (platform_fee_cents <= amount_cents)
);

create index if not exists orders_student on orders (student_id);

-- The row that unlocks content. Written by the Stripe webhook and by nothing else.
create table if not exists entitlements (
  id         uuid primary key default gen_random_uuid(),
  student_id uuid not null references profiles (id) on delete cascade,
  lesson_id  uuid not null references custom_lessons (id) on delete cascade,
  order_id   uuid references orders (id) on delete set null,
  granted_at timestamptz not null default now(),
  unique (student_id, lesson_id)
);

-- ---------------------------------------------------------------------------
-- lesson_submissions
-- ---------------------------------------------------------------------------

do $$ begin create type submission_status as enum ('submitted', 'reviewed'); exception when duplicate_object then null; end $$;

create table if not exists lesson_submissions (
  id           uuid primary key default gen_random_uuid(),
  lesson_id    uuid not null references custom_lessons (id) on delete cascade,
  student_id   uuid not null references profiles (id) on delete cascade,
  answers      jsonb not null default '[]'::jsonb,
  quiz_score   integer not null default 0,
  quiz_total   integer not null default 0,
  status       submission_status not null default 'submitted',
  submitted_at timestamptz not null default now(),
  reviewed_at  timestamptz,
  reviewer_id  uuid references profiles (id),
  feedback     text,
  awarded_xp   integer,
  unique (lesson_id, student_id)
);

-- ---------------------------------------------------------------------------
-- helpers
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- profiles are created by Auth, not by the client
-- ---------------------------------------------------------------------------
-- Every policy below reads profiles, and so does the admin check, so a signed-in
-- person without a row here can do nothing at all. Letting the browser insert its
-- own row would mean letting it choose its own `role` and `is_admin`, which is the
-- one thing that must never be client-supplied — so a trigger does it instead.
--
-- role is hardcoded to 'student'. Becoming a mentor happens through an approved
-- application, and nothing a person types at signup can shortcut that.

create or replace function handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, name, avatar, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    upper(left(coalesce(new.raw_user_meta_data ->> 'name', new.email), 2)),
    'student'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

create or replace function is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select p.is_admin from profiles p where p.id = auth.uid()), false)
$$;

create or replace function owns_lesson(lesson uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from custom_lessons l where l.id = lesson and l.author_id = auth.uid())
$$;

create or replace function has_entitlement(lesson uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from entitlements e where e.lesson_id = lesson and e.student_id = auth.uid())
$$;

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
-- Every table is locked by default. Note what is absent as much as what is present:
-- there is no insert/update policy on entitlements or orders for any normal role, so even
-- a leaked anon key cannot mint an entitlement. Only the service role, used solely by the
-- Stripe webhook, bypasses RLS.

-- Dropped first so the whole file can be run again after a correction, rather than
-- aborting on the first policy that already exists.
drop policy if exists profiles_read on profiles;
drop policy if exists profiles_update_self on profiles;
drop policy if exists applications_read_own on mentor_applications;
drop policy if exists applications_insert_own on mentor_applications;
drop policy if exists applications_review on mentor_applications;
drop policy if exists accounts_read_own on mentor_accounts;
drop policy if exists lessons_read_published on custom_lessons;
drop policy if exists lessons_write_own on custom_lessons;
drop policy if exists tasks_author_only on custom_tasks;
drop policy if exists orders_read_own on orders;
drop policy if exists entitlements_read_own on entitlements;
drop policy if exists submissions_read on lesson_submissions;
drop policy if exists submissions_insert_own on lesson_submissions;
drop policy if exists submissions_grade on lesson_submissions;

alter table profiles             enable row level security;
alter table mentor_applications  enable row level security;
alter table mentor_accounts      enable row level security;
alter table custom_lessons       enable row level security;
alter table custom_tasks         enable row level security;
alter table orders               enable row level security;
alter table entitlements         enable row level security;
alter table lesson_submissions   enable row level security;

-- profiles: readable by signed-in users (names appear on lessons and reviews);
-- writable only by the owner, and never to grant themselves admin or mentor.
create policy profiles_read on profiles for select to authenticated using (true);
create policy profiles_update_self on profiles for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid() and is_admin = (select p.is_admin from profiles p where p.id = auth.uid())
              and role = (select p.role from profiles p where p.id = auth.uid()));

-- mentor_applications: an applicant sees and files their own; admins see all.
create policy applications_read_own on mentor_applications for select to authenticated
  using (user_id = auth.uid() or is_admin());
create policy applications_insert_own on mentor_applications for insert to authenticated
  with check (user_id = auth.uid() and status = 'pending');
-- Only an admin may move an application out of pending. An applicant approving themselves
-- is the whole failure this table exists to prevent.
create policy applications_review on mentor_applications for update to authenticated
  using (is_admin()) with check (is_admin());

create policy accounts_read_own on mentor_accounts for select to authenticated
  using (user_id = auth.uid() or is_admin());

-- custom_lessons: a published lesson is discoverable by anyone signed in — that is the
-- storefront, and price and title must be visible before purchase. material_path is a
-- Storage key, useless without a signed URL, which the server issues only on entitlement.
create policy lessons_read_published on custom_lessons for select to authenticated
  using (published or author_id = auth.uid() or is_admin());
create policy lessons_write_own on custom_lessons for all to authenticated
  using (author_id = auth.uid()) with check (author_id = auth.uid());

-- custom_tasks: authors and admins only. Students never read this table; they receive
-- tasks through /api/lesson-content, which strips answer_index and checks entitlement.
create policy tasks_author_only on custom_tasks for all to authenticated
  using (owns_lesson(lesson_id) or is_admin()) with check (owns_lesson(lesson_id));

-- orders and entitlements: readable by the buyer, writable by no one. The webhook uses
-- the service role, which is not subject to these policies.
create policy orders_read_own on orders for select to authenticated
  using (student_id = auth.uid() or is_admin());
create policy entitlements_read_own on entitlements for select to authenticated
  using (student_id = auth.uid() or is_admin());

-- submissions: a student writes their own; the lesson's author reads and grades.
create policy submissions_read on lesson_submissions for select to authenticated
  using (student_id = auth.uid() or owns_lesson(lesson_id) or is_admin());
-- Entitlements are only ever written for a lesson somebody paid for, so requiring one here
-- made a FREE mentor lesson impossible to submit: there is no row and there never will be.
-- A lesson priced at zero is open to anyone who can see it, which is what published means.
create policy submissions_insert_own on lesson_submissions for insert to authenticated
  with check (
    student_id = auth.uid()
    and (
      has_entitlement(lesson_id)
      or exists (select 1 from custom_lessons l where l.id = lesson_id and l.published and l.price_cents <= 0)
    )
  );
create policy submissions_grade on lesson_submissions for update to authenticated
  using (owns_lesson(lesson_id)) with check (owns_lesson(lesson_id));

-- ---------------------------------------------------------------------------
-- Storage
-- ---------------------------------------------------------------------------
-- Both buckets are private. mentor-docs holds identity documents: it is readable only by
-- admins reviewing an application, through short-lived signed URLs, and never listed.

insert into storage.buckets (id, name, public) values
  ('lesson-materials', 'lesson-materials', false),
  ('mentor-docs', 'mentor-docs', false)
on conflict (id) do nothing;

-- Storage policies are wrapped for two reasons.
--
-- Re-running: `create policy` has no `if not exists`, so a second run of this file would
-- abort partway through. Dropping first makes the migration idempotent, which matters
-- because the usual way to apply it is pasting into the SQL editor and running it again
-- after fixing something.
--
-- Ownership: storage.objects belongs to the storage extension, and on some projects the
-- SQL editor's role cannot add policies to it. That failure is recoverable — the buckets
-- are already private, so the only loss is per-user path isolation, which can be set from
-- Dashboard > Storage > Policies. Raising a notice beats aborting the whole migration and
-- leaving the database half-built.

do $$
begin
  drop policy if exists material_upload on storage.objects;
  drop policy if exists material_manage_own on storage.objects;
  drop policy if exists material_delete_own on storage.objects;
  drop policy if exists docs_upload_own on storage.objects;
  drop policy if exists docs_read_admin on storage.objects;

  -- Mentors upload material under their own user id prefix.
  create policy material_upload on storage.objects for insert to authenticated
    with check (bucket_id = 'lesson-materials' and (storage.foldername(name))[1] = auth.uid()::text);
  create policy material_manage_own on storage.objects for update to authenticated
    using (bucket_id = 'lesson-materials' and (storage.foldername(name))[1] = auth.uid()::text);
  create policy material_delete_own on storage.objects for delete to authenticated
    using (bucket_id = 'lesson-materials' and (storage.foldername(name))[1] = auth.uid()::text);

  -- Identity documents: the applicant may upload, only an admin may read.
  create policy docs_upload_own on storage.objects for insert to authenticated
    with check (bucket_id = 'mentor-docs' and (storage.foldername(name))[1] = auth.uid()::text);
  create policy docs_read_admin on storage.objects for select to authenticated
    using (bucket_id = 'mentor-docs' and is_admin());
exception
  when insufficient_privilege then
    raise notice 'Could not create storage policies (insufficient privilege). The buckets are still private; add the policies from Dashboard > Storage > Policies.';
end $$;

-- ========================================================================================
-- 0002_progress.sql
-- ========================================================================================

-- Progress schema.
--
-- 0001 drew the line at money and left progress in the browser, on the grounds that nobody
-- gains by forging their own streak. That is still true of forging. It is not true of losing:
-- a cleared browser is a cleared account, progress on one device is invisible on the next,
-- and a mentor can only see projects submitted from the same browser they are reviewing in.
--
-- Three shapes, because three different questions get asked of this data:
--   student_profiles  one row per learner   — who is this and where are they (boot, leaderboard)
--   lesson_progress   one row per lesson    — what happened and when (cohorts, adaptive paths)
--   xp_ledger         one row per award     — why they have this much, and pay it once
--
-- A single JSONB document was the other candidate. It is rejected on the middle row: the
-- question a mentor dashboard asks is "which lesson is this class stuck on", which against a
-- document is a full scan and a jsonb_array_elements for every question anyone ever asks. The
-- id arrays in StudentProfile also throw away the column analytics wants most — the timestamp.
-- `completedLessonIds` says a lesson was finished. It cannot say it took four days.

-- ---------------------------------------------------------------------------
-- student_profiles
-- ---------------------------------------------------------------------------
-- The summary read on boot: one row, one round trip, and the leaderboard is an index scan
-- rather than an aggregate over the ledger. `xp` is a cache of sum(xp_ledger.amount),
-- maintained by the trigger below and writable by nothing else — see the update policy.
--
-- Course ids are text and not foreign keys: courses live in code, not in rows. A constraint
-- here would mean shipping the curriculum to the database twice.

create table if not exists student_profiles (
  user_id             uuid primary key references profiles (id) on delete cascade,
  xp                  integer not null default 0 check (xp >= 0),
  streak              integer not null default 0 check (streak >= 0),
  last_active_date    timestamptz not null default now(),
  current_course_id   text not null default '',
  enrolled_course_ids text[] not null default '{}',
  goal                text not null default 'goal_complete_first_lesson',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists student_profiles_xp on student_profiles (xp desc);

-- ---------------------------------------------------------------------------
-- lesson_progress
-- ---------------------------------------------------------------------------
-- Three timestamps rather than three booleans, and one row rather than three id arrays on the
-- profile. `passedCheckLessonIds`, `completedLessonIds` and `completedChallengeIds` are the
-- same fact about the same lesson recorded in three places; here they are three columns of
-- one row, each carrying when it happened. When is the entire input to an adaptive path, and
-- a boolean discards it for no saving.
--
-- Curriculum lessons only. A mentor-written lesson's progress is a lesson_submissions row,
-- which 0001 already created.

create table if not exists lesson_progress (
  user_id                uuid not null references profiles (id) on delete cascade,
  lesson_id              text not null,
  course_id              text not null,
  first_seen_at          timestamptz not null default now(),
  check_passed_at        timestamptz,
  completed_at           timestamptz,
  challenge_completed_at timestamptz,
  primary key (user_id, lesson_id)
);

-- The cohort read: how far a class has got through a given lesson.
create index if not exists lesson_progress_by_lesson on lesson_progress (lesson_id) where completed_at is not null;
create index if not exists lesson_progress_by_course on lesson_progress (course_id, user_id);

-- ---------------------------------------------------------------------------
-- xp_ledger
-- ---------------------------------------------------------------------------
-- `awardXp` refuses a second award for the same kind and ref. That guard lives in one function
-- deliberately — guarding each caller separately is how a resubmitted project came to pay
-- twice — but it cannot survive as a client-side check once two devices exist. It moves here,
-- to the only place both devices agree on.
--
-- Two unique keys doing two different jobs, and both are needed:
--   op_id                   a retry after an unknown outcome collides instead of paying twice.
--                           The request that timed out may well have committed.
--   (user_id, kind, ref_id) a second award for the same thing is impossible even from another
--                           device with a different op_id. This is awardXp, in the database.
--
-- `reason` is a dictionary key and `vars` its interpolation, never a finished sentence — the
-- ledger would otherwise be frozen in whatever language was active when it was written.

do $$ begin
  create type xp_kind as enum ('lesson', 'assignment', 'challenge', 'submission', 'approval', 'achievement', 'competition');
exception when duplicate_object then null; end $$;

create table if not exists xp_ledger (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles (id) on delete cascade,
  amount     integer not null check (amount >= 0),
  reason     text not null,
  vars       jsonb,
  kind       xp_kind not null,
  ref_id     text,
  op_id      uuid not null unique,
  created_at timestamptz not null default now()
);

create unique index if not exists xp_ledger_paid_once on xp_ledger (user_id, kind, ref_id) where ref_id is not null;
create index if not exists xp_ledger_recent on xp_ledger (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- the running total
-- ---------------------------------------------------------------------------
-- `xp` is never sent by a client and never updated by one. It moves only when a ledger row
-- lands, which makes the unique index above the double-count guard for the total as well as
-- for the ledger. One choke point, which is the same argument awardXp makes.

create or replace function xp_ledger_apply()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into student_profiles (user_id) values (new.user_id) on conflict (user_id) do nothing;
  update student_profiles set xp = xp + new.amount, updated_at = now() where user_id = new.user_id;
  return new;
end $$;

drop trigger if exists xp_ledger_totals on xp_ledger;
create trigger xp_ledger_totals after insert on xp_ledger for each row execute function xp_ledger_apply();

-- ---------------------------------------------------------------------------
-- helpers
-- ---------------------------------------------------------------------------
-- `selectors.mentorStats` says one academy, one roster: a mentor is responsible for every
-- student unless a group says otherwise. This says the same rather than inventing a cohort
-- boundary the application does not have.

create or replace function is_mentor()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select p.role = 'mentor' from profiles p where p.id = auth.uid()), false)
$$;

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
-- `create policy` has no `if not exists`, so a second run of this file would abort without
-- these drops. 0001 takes the same precaution for the same reason.

drop policy if exists student_profiles_read on student_profiles;
drop policy if exists student_profiles_insert_own on student_profiles;
drop policy if exists student_profiles_update_own on student_profiles;
drop policy if exists lesson_progress_read on lesson_progress;
drop policy if exists lesson_progress_insert_own on lesson_progress;
drop policy if exists lesson_progress_update_own on lesson_progress;
drop policy if exists xp_ledger_read on xp_ledger;
drop policy if exists xp_ledger_insert_own on xp_ledger;

alter table student_profiles enable row level security;
alter table lesson_progress  enable row level security;
alter table xp_ledger        enable row level security;

create policy student_profiles_read on student_profiles for select to authenticated
  using (user_id = auth.uid() or is_mentor() or is_admin());
create policy student_profiles_insert_own on student_profiles for insert to authenticated
  with check (user_id = auth.uid() and xp = 0);

-- `xp` is pinned to its current value, exactly as 0001 pins `is_admin` on profiles. A learner
-- may move their goal and their course. They may not move their score.
create policy student_profiles_update_own on student_profiles for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and xp = (select sp.xp from student_profiles sp where sp.user_id = auth.uid()));

create policy lesson_progress_read on lesson_progress for select to authenticated
  using (user_id = auth.uid() or is_mentor() or is_admin());
create policy lesson_progress_insert_own on lesson_progress for insert to authenticated
  with check (user_id = auth.uid());
create policy lesson_progress_update_own on lesson_progress for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
-- No delete policy, deliberately: progress is not un-made.

create policy xp_ledger_read on xp_ledger for select to authenticated
  using (user_id = auth.uid() or is_mentor() or is_admin());

-- A learner records what they did. `approval` and `competition` are absent on purpose: those
-- are somebody else's decision about you, and must arrive through a route holding the service
-- role rather than from the browser of the person being decided about.
create policy xp_ledger_insert_own on xp_ledger for insert to authenticated
  with check (user_id = auth.uid() and kind in ('lesson', 'assignment', 'challenge', 'achievement', 'submission'));

-- No update and no delete policy for anybody, including admins. A ledger that can be edited
-- is not a ledger.

-- ========================================================================================
-- 0003_projects.sql
-- ========================================================================================

-- Projects and the reviews of them.
--
-- The review loop is the product's core claim — a real person reads your work — and until now
-- it ran entirely in one browser. A mentor could only see projects submitted from the same
-- browser they were reviewing in, which is to say: never, since the student uses their own.
--
-- This is shaped differently from 0002 on purpose. Progress is a grow-only set belonging to
-- one learner, so it syncs as idempotent operations. A project is a document that two people
-- take turns writing to: the student submits and resubmits it, the mentor claims it and
-- decides on it. Operations would need a merge rule for every field; rows with a clear owner
-- per column do not.

do $$ begin
  create type project_status as enum ('draft', 'submitted', 'under_review', 'approved', 'needs_changes');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- projects
-- ---------------------------------------------------------------------------
-- `course_id` and `lesson_id` are text and not foreign keys for the same reason as in 0002:
-- lessons live in code or in custom_lessons, and a constraint here would have to choose one.
--
-- Attachments are jsonb rather than a table. They are read only as a whole, always with their
-- project, and never queried across projects — a join would buy nothing.

create table if not exists projects (
  id           uuid primary key default gen_random_uuid(),
  author_id    uuid not null references profiles (id) on delete cascade,
  title        text not null,
  description  text not null default '',
  code         text not null default '',
  notes        text not null default '',
  course_id    text not null default '',
  lesson_id    text not null default '',
  attachments  jsonb not null default '[]'::jsonb,
  tags         text[] not null default '{}',
  status       project_status not null default 'draft',
  created_at   timestamptz not null default now(),
  submitted_at timestamptz,
  reviewed_at  timestamptz,
  reviewer_id  uuid references profiles (id),
  likes        integer not null default 0 check (likes >= 0),
  views        integer not null default 0 check (views >= 0)
);

-- The review queue: what is waiting, oldest first.
create index if not exists projects_queue on projects (submitted_at) where status in ('submitted', 'under_review');
create index if not exists projects_by_author on projects (author_id, created_at desc);
-- The public gallery only ever shows approved work.
create index if not exists projects_approved on projects (reviewed_at desc) where status = 'approved';

-- ---------------------------------------------------------------------------
-- project_feedback
-- ---------------------------------------------------------------------------
-- Append-only, and deliberately so. A review is a record of what somebody said at a moment,
-- and a student who has read it should not find it edited afterwards. Requesting changes and
-- then approving leaves two rows, which is the history of the project rather than a mistake.

do $$ begin
  create type review_decision as enum ('approved', 'needs_changes', 'comment');
exception when duplicate_object then null; end $$;

create table if not exists project_feedback (
  id         uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects (id) on delete cascade,
  mentor_id  uuid not null references profiles (id) on delete cascade,
  decision   review_decision not null,
  message    text not null,
  -- Three axes any subject can be scored on. It used to be wiring, code and documentation,
  -- which assumed the subject was electronics.
  rubric     jsonb,
  created_at timestamptz not null default now()
);

create index if not exists project_feedback_by_project on project_feedback (project_id, created_at);

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

drop policy if exists projects_read on projects;
drop policy if exists projects_insert_own on projects;
drop policy if exists projects_update_own on projects;
drop policy if exists projects_review on projects;
drop policy if exists feedback_read on project_feedback;
drop policy if exists feedback_write_mentor on project_feedback;

alter table projects         enable row level security;
alter table project_feedback enable row level security;

-- Your own work, anything approved, and — for a mentor — everything. The gallery shows
-- approved work to everyone, which is what makes it a gallery.
create policy projects_read on projects for select to authenticated
  using (author_id = auth.uid() or status = 'approved' or is_mentor() or is_admin());

create policy projects_insert_own on projects for insert to authenticated
  with check (author_id = auth.uid() and status in ('draft', 'submitted') and reviewer_id is null and reviewed_at is null);

-- A student may edit their own work and hand it in. They may not decide on it: `status` is
-- pinned to the states they are allowed to put it in, and the reviewer columns to null.
-- Approving your own project would otherwise be one PATCH away.
create policy projects_update_own on projects for update to authenticated
  using (author_id = auth.uid() and status in ('draft', 'submitted', 'needs_changes'))
  with check (author_id = auth.uid() and status in ('draft', 'submitted') and reviewer_id is null and reviewed_at is null);

-- A mentor may claim and decide, and nothing else. The work itself is not theirs to rewrite,
-- but Postgres has no per-column update policy — so the route, not this policy, is what keeps
-- a mentor off the body of the work, and the route is the only thing holding a service role.
create policy projects_review on projects for update to authenticated
  using (is_mentor() and status in ('submitted', 'under_review'))
  with check (is_mentor());

create policy feedback_read on project_feedback for select to authenticated
  using (
    is_mentor()
    or is_admin()
    or exists (select 1 from projects p where p.id = project_id and p.author_id = auth.uid())
  );

-- Only a mentor writes a review, and only under their own name.
create policy feedback_write_mentor on project_feedback for insert to authenticated
  with check (mentor_id = auth.uid() and is_mentor());

-- No update and no delete on feedback, for anybody. See the note above the table.

-- ========================================================================================
-- 0004_notifications.sql
-- ========================================================================================

-- Notifications that one person causes for another.
--
-- Every notification in this app is created by a pure reducer, in the browser of whoever
-- performed the action. That works exactly once: when the person who acts and the person who
-- is told are the same. "You unlocked an achievement" is written in the browser that unlocked
-- it, and is right there for its only reader.
--
-- The ones that matter most are the other kind. A mentor approves a project and `notify()`
-- writes a row addressed to the student — into the mentor's localStorage, where the student
-- will never be. The review loop is the product's core claim, and its ending was invisible.
--
-- So this table deliberately does not hold every notification. It holds the ones that cross
-- from one account to another, and the client merges them with the local ones on load. Two
-- sources with no overlap and no merge rule: a row lands here only because a route put it
-- here on someone else's behalf, and those are exactly the rows a reducer cannot deliver.

create table if not exists notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles (id) on delete cascade,
  -- Dictionary keys, not sentences — the same discipline as the client's Notification type.
  -- The reader's language is not known when the row is written, and may change afterwards.
  title      text not null,
  body       text not null,
  vars       jsonb not null default '{}'::jsonb,
  kind       text not null,
  href       text,
  created_at timestamptz not null default now(),
  -- When, not whether. A timestamp costs the same as a boolean and answers more later.
  read_at    timestamptz
);

-- The only query there is: this person's inbox, newest first.
create index if not exists notifications_inbox on notifications (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

drop policy if exists notifications_read_own on notifications;
drop policy if exists notifications_write_staff on notifications;
drop policy if exists notifications_mark_read on notifications;

alter table notifications enable row level security;

create policy notifications_read_own on notifications for select to authenticated
  using (user_id = auth.uid());

-- Writing a row for somebody else is the whole point, so the check cannot be
-- `user_id = auth.uid()`. It is limited instead to the two roles that act on other people:
-- a mentor deciding on work, an admin deciding on an application. A student has no reason to
-- put anything in anyone's inbox, including their own — their notifications are local.
create policy notifications_write_staff on notifications for insert to authenticated
  with check (is_mentor() or is_admin());

-- Marking your own as read. Postgres cannot pin this to `read_at` alone — policies apply to
-- a row, not a column — so the route is what keeps it to that one field. Rewriting the text
-- of a notification addressed to you is a lie you tell yourself, which is why this is left
-- to the route rather than given a service role.
create policy notifications_mark_read on notifications for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- No delete policy. An inbox that can be emptied invisibly is worse than one that grows.

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------
-- The bell should ring while the page is open, not on the next reload. Realtime replays this
-- table's changes over the socket the client already holds, and it honours the policies above
-- — a subscriber is only sent rows `notifications_read_own` would have let them select — so
-- the feed needs no filter of its own to be safe.
--
-- Wrapped because the publication may already carry the table, and on a project where
-- Realtime was never enabled it may not exist at all. Neither is a reason to fail a
-- migration whose actual work is the table above.
do $$ begin
  alter publication supabase_realtime add table notifications;
exception
  when duplicate_object then null;
  when undefined_object then raise notice 'supabase_realtime publication not found; live notifications stay off';
end $$;

-- ========================================================================================
-- 0005_column_ownership.sql
-- ========================================================================================

-- Takes away two write rights the browser should never have had.
--
-- Three places in this schema justified a wide `update` policy by saying that the API route
-- restricts which columns are written. That is true of the route and false of the database.
-- `src/lib/supabase.ts` hands the browser an authenticated client on purpose — it is how the
-- app reads profiles and signs in — so anyone can open devtools and issue the update the
-- route would have refused to write. The route is one client, not the boundary.
--
-- Postgres has no per-column update policy. It does have two other tools, and each fits one
-- of these cases exactly.

-- ---------------------------------------------------------------------------
-- projects: the mentor's update right goes away entirely
-- ---------------------------------------------------------------------------
-- `projects_review` allowed `update` to any mentor on any submitted project, checking only
-- that the writer is a mentor. Every column was in reach:
--
--   supabase.from('projects').update({ code: '…', author_id: <mine>, status: 'approved' })
--
-- — rewrite a student's submission, take the authorship, approve it into the public gallery.
-- Nothing in the schema said no.
--
-- There is no narrower policy to write, because the distinction is per column and policies
-- are per row. So the decision moves out of the browser's reach: `api/projects.ts` PATCH now
-- writes with the service role, having identified the caller as a mentor from `profiles`.
-- A mentor's browser keeps its read rights and loses its write rights.
drop policy if exists projects_review on projects;

-- Students keep theirs. `projects_update_own` is already column-safe by construction: its
-- `with check` pins `status` to the two states a student may set and both reviewer columns
-- to null, so there is no column left to abuse.

-- ---------------------------------------------------------------------------
-- notifications: read_at and nothing else
-- ---------------------------------------------------------------------------
-- Here the right tool is a column privilege rather than a policy. Only one party ever updates
-- a notification — its owner — so the grant can be narrowed for everybody at once, which is
-- what `authenticated` being a single role otherwise makes impossible.
--
-- RLS still decides *which* rows (`notifications_mark_read`, unchanged); this decides which
-- columns, and now the comment on that policy is a fact rather than a promise about a route.
revoke update on notifications from authenticated;
grant update (read_at) on notifications to authenticated;

-- ---------------------------------------------------------------------------
-- lesson_submissions: the same treatment, before anything depends on it
-- ---------------------------------------------------------------------------
-- Nothing reads this table yet — submissions still live in the student's browser — which is
-- the only reason these were not exploitable. Two holes, both from 0001:
--
--   `submissions_insert_own` lets a student insert their own row with any `status` and any
--   `awarded_xp`, so `{status: 'reviewed', awarded_xp: 99999}` was one call away.
--   `submissions_grade` lets the lesson's author update the row, including `answers` and
--   `student_id` — a mentor could rewrite what a student submitted, or reassign it.
--
-- Column privileges split it cleanly: a student writes the answer columns, a mentor writes
-- the grading columns, and the row policies keep deciding whose rows either may touch.
do $$ begin
  revoke insert, update on lesson_submissions from authenticated;
  grant insert (lesson_id, student_id, answers, quiz_total, submitted_at) on lesson_submissions to authenticated;
  grant update (status, quiz_score, awarded_xp, feedback, reviewed_at, reviewer_id) on lesson_submissions to authenticated;
exception when undefined_table then raise notice 'lesson_submissions not found; skipped';
end $$;

-- ========================================================================================
-- 0006_open_teaching.sql
-- ========================================================================================

-- Anyone may teach here.
--
-- The application desk is gone. It was built for a robotics academy where a named adult with
-- documents was approved by a reviewer before handling children's work — a real answer to a
-- real question, and the wrong shape for an open marketplace where the platform's job is to
-- carry other people's courses, not to vet them first.
--
-- What replaces it is the thing every open marketplace actually relies on: publishing under
-- your own name, a review loop students can see, and the ability to take money only through
-- an account Stripe has verified. Money still has a gate; teaching does not.
--
-- The tables from 0001 stay. `mentor_applications` holds rows somebody filed in good faith,
-- and dropping a table to tidy up a UI is how history gets lost. Nothing reads it any more.

-- ---------------------------------------------------------------------------
-- profiles: a person may now make themselves a mentor
-- ---------------------------------------------------------------------------
-- The old policy pinned `role` to its current value, because the only legitimate way to
-- change it was an admin route acting on an approved application. With that gone, pinning it
-- would mean nobody could ever teach.
--
-- `is_admin` stays pinned, and that is the line that matters. Admin decides who is admin;
-- anyone decides whether they teach. The enum has exactly two values, so `role in (...)` is
-- not a restriction so much as a statement that this is the whole of it.
drop policy if exists profiles_update_self on profiles;
create policy profiles_update_self on profiles for update to authenticated
  using (id = auth.uid())
  with check (
    id = auth.uid()
    and is_admin = (select p.is_admin from profiles p where p.id = auth.uid())
    and role in ('student', 'mentor')
  );

-- ========================================================================================
-- 0007_authority.sql
-- ========================================================================================

-- Repairs two things that `0006_open_teaching.sql` quietly broke.
--
-- Letting anyone make themselves a mentor was the right product decision and the wrong
-- security one, because `is_mentor()` was being used for two different jobs. As a
-- *capability* — may this person write and publish a course — it is still exactly right, and
-- now costs one click, as intended. As *authority over somebody else's row* it has become
-- meaningless: a predicate any signed-in account can switch on for itself grants nothing.
--
-- Every policy written as `is_mentor()` for the second purpose therefore has to go. There
-- were two, and one of them was a hole with a name.

-- ---------------------------------------------------------------------------
-- notifications: nobody writes into somebody else's inbox from a browser
-- ---------------------------------------------------------------------------
-- `notifications_write_staff` allowed an insert by anyone `is_mentor()`, on the reasoning
-- that mentors act on other people. After 0006 that is everyone, so the table was an open
-- relay: arbitrary title, arbitrary body, arbitrary `href`, delivered into any account's
-- inbox and rendered as if the platform had sent it. "Your payment failed, click here" is
-- two lines from devtools.
--
-- It is not fixable with a narrower predicate, because there is no honest one: mentorship is
-- self-declared by design now. So the browser loses the right entirely. The three places
-- that legitimately notify somebody else — a review decided, a mentor application answered,
-- a demand request fulfilled — all run in `api/`, where a service role is available and its
-- use is already the documented pattern for "writes rows no user may write".
--
-- Note there is still no delete policy, deliberately: an inbox that can be emptied invisibly
-- is worse than one that grows. That is precisely why nothing arbitrary may be put in it.
drop policy if exists notifications_write_staff on notifications;

-- ---------------------------------------------------------------------------
-- custom_lessons: publishing is not a column the author may write
-- ---------------------------------------------------------------------------
-- `lessons_write_own` is `for all`, so an author holds update on every column of their own
-- lesson — including `published`. `api/lessons.ts` guards a priced publish behind
-- `requireSellingMentor`, but a guard in a route is advice when the browser can write the
-- same column directly:
--
--   supabase.from('custom_lessons').update({ published: true }).eq('id', mine)
--
-- — and the lesson is in the storefront at whatever price, with no Stripe account behind it
-- and no way for the money to arrive. The `0005` treatment applies: keep the row policy,
-- narrow the columns, and let the route own the one field it actually gates.
revoke update on custom_lessons from authenticated;
grant update (title, summary, material_path, material_name, material_mime, material_size, price_cents, currency, updated_at)
  on custom_lessons to authenticated;

-- `published` is deliberately absent from that list, and so are `id`, `author_id` and
-- `created_at`. Publishing now happens only through `api/lessons.ts`, which holds the
-- service role and checks Stripe first.

-- ========================================================================================
-- 0008_demand.sql
-- ========================================================================================

-- The demand board: what people want taught, before anybody has taught it.
--
-- Every marketplace starts empty, and the usual way out is to buy the first courses. This
-- platform cannot, so it inverts the order instead: a student publishes what they want to
-- learn, other people vote on it, and a mentor answers a brief that already has an audience
-- attached. A request with forty votes is a course with forty people waiting for it.
--
-- Deliberately not an escrow. `budget_cents` is what the asker says they would pay, and no
-- money is held against it — a pledge would need live Stripe, refunds, and a policy for the
-- mentor who delivers something nobody wanted after all. Stating a budget costs nothing and
-- tells a mentor most of what they need to decide.

do $$ begin
  create type request_status as enum ('open', 'fulfilled', 'withdrawn');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- course_requests
-- ---------------------------------------------------------------------------
-- There is no `direction` column. `directionOf()` in `src/lib/discovery.ts` reads a subject
-- off a title and a summary, and works on a request unchanged — so the board filters by the
-- same derivation the catalogue does. A stored field would be a second answer to the same
-- question, free text that never quite matches a `DirectionId`, and the file that derives it
-- says why: a filter nobody populates is a filter that returns nothing.
--
-- `votes` is a cached count maintained by trigger, exactly as `student_profiles.xp` caches
-- the ledger. The vote rows are the truth; this column exists so the board can be ordered
-- without counting a join on every read.

create table if not exists course_requests (
  id           uuid primary key default gen_random_uuid(),
  author_id    uuid not null references profiles (id) on delete cascade,
  title        text not null check (char_length(title) between 4 and 140),
  body         text not null default '' check (char_length(body) <= 2000),
  -- Minor units, like every other amount here. 0 means "no budget stated", not "free".
  budget_cents integer not null default 0 check (budget_cents >= 0 and budget_cents <= 100000000),
  currency     char(3) not null default 'usd',
  deadline     date,
  status       request_status not null default 'open',
  votes        integer not null default 0 check (votes >= 0),
  created_at   timestamptz not null default now()
);

-- The board: what is still open, loudest first.
create index if not exists course_requests_board on course_requests (votes desc, created_at desc) where status = 'open';
create index if not exists course_requests_by_author on course_requests (author_id, created_at desc);

-- ---------------------------------------------------------------------------
-- course_request_votes
-- ---------------------------------------------------------------------------
-- One row per person per request, and the primary key is what enforces that — a second vote
-- collides rather than counting twice. Votes can be taken back, so unlike the XP ledger this
-- one allows delete; what it does not allow is update, because there is nothing in a vote to
-- change and an updatable row is a row that can be moved to somebody else's request.

create table if not exists course_request_votes (
  request_id uuid not null references course_requests (id) on delete cascade,
  user_id    uuid not null references profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (request_id, user_id)
);

-- Recomputed, not incremented. A counter that adds and subtracts drifts the first time a
-- path is missed; a count over a table with a two-column primary key cannot disagree with
-- itself, and at board-sized row counts the subquery is free. `security definer` because the
-- voter does not own the request row and must not be able to write it directly — the grant
-- below revokes exactly that.
create or replace function course_request_votes_apply() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  target uuid := coalesce(new.request_id, old.request_id);
begin
  update course_requests
     set votes = (select count(*) from course_request_votes v where v.request_id = target)
   where id = target;
  return coalesce(new, old);
end $$;

drop trigger if exists course_request_votes_count on course_request_votes;
create trigger course_request_votes_count
  after insert or delete on course_request_votes
  for each row execute function course_request_votes_apply();

-- ---------------------------------------------------------------------------
-- request_fulfilments
-- ---------------------------------------------------------------------------
-- A join table rather than a `fulfilled_lesson_id` column on the request, because both sides
-- are many: one course can answer several requests that were asking for the same thing, and
-- one request can be answered by more than one mentor — which is competition, and good.

create table if not exists request_fulfilments (
  request_id  uuid not null references course_requests (id) on delete cascade,
  lesson_id   uuid not null references custom_lessons (id) on delete cascade,
  mentor_id   uuid not null references profiles (id) on delete cascade,
  created_at  timestamptz not null default now(),
  -- Set the first time the voters are told. Non-null means: never again.
  announced_at timestamptz,
  primary key (request_id, lesson_id)
);

create index if not exists request_fulfilments_by_lesson on request_fulfilments (lesson_id);

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

drop policy if exists requests_read on course_requests;
drop policy if exists requests_insert_own on course_requests;
drop policy if exists requests_update_own on course_requests;
drop policy if exists request_votes_read on course_request_votes;
drop policy if exists request_votes_insert_own on course_request_votes;
drop policy if exists request_votes_delete_own on course_request_votes;
drop policy if exists fulfilments_read on request_fulfilments;
drop policy if exists fulfilments_insert_own_lesson on request_fulfilments;

alter table course_requests      enable row level security;
alter table course_request_votes enable row level security;
alter table request_fulfilments  enable row level security;

-- The board is public to signed-in users. A demand board nobody can read is a suggestion box.
create policy requests_read on course_requests for select to authenticated using (true);

create policy requests_insert_own on course_requests for insert to authenticated
  with check (author_id = auth.uid() and status = 'open' and votes = 0);

-- The author may edit their own wording and withdraw it. They may not touch `votes`, and
-- the column grant below is what actually stops them — a policy applies to a row, not to a
-- column, so `with check` cannot express "every field but this one".
create policy requests_update_own on course_requests for update to authenticated
  using (author_id = auth.uid())
  with check (author_id = auth.uid());

revoke update on course_requests from authenticated;
-- `status` is absent on purpose: withdrawing goes through the route, which is also where a
-- request stops being announced. `votes` is absent because it is the trigger's, and
-- `author_id` and `created_at` because they are the row's identity.
grant update (title, body, budget_cents, deadline) on course_requests to authenticated;

-- Votes are readable so the interface can show what you already voted for. Who voted for
-- what is not sensitive here; that a request has support is the entire point of it.
create policy request_votes_read on course_request_votes for select to authenticated using (true);

create policy request_votes_insert_own on course_request_votes for insert to authenticated
  with check (user_id = auth.uid());

create policy request_votes_delete_own on course_request_votes for delete to authenticated
  using (user_id = auth.uid());

-- No update policy, and the right is revoked outright. There is nothing in a vote to change
-- — the whole row is its primary key — and an updatable vote is a vote that can be moved to
-- somebody else's request.
revoke update on course_request_votes from authenticated;

create policy fulfilments_read on request_fulfilments for select to authenticated using (true);

-- No insert policy for the browser at all.
--
-- Answering a request is not just a row: it notifies everyone who voted, with a link to the
-- answerer's lesson. That is a broadcast primitive with a marketing incentive attached, and
-- `notifications` has no delete policy — an announcement cannot be recalled. So it goes
-- through `api/requests.ts`, which holds the service role, checks `author_id` and
-- `published` on the lesson itself, and announces a given request exactly once.
--
-- `announced_at` is what makes "exactly once" a property of the data rather than of the
-- route: publish, unpublish and republish is otherwise an unlimited megaphone.

-- ========================================================================================
-- 0009_reputation.sql
-- ========================================================================================

-- Numbers about a course that the course's author did not write.
--
-- Every marketplace sells on stars, and stars have a known problem: the seller's own
-- customers write them, which is why every platform that uses them also runs a fraud filter
-- on them. The conversion research points somewhere else anyway — completion rate persuades
-- better than a rating — and completion rate is buried in instructor analytics everywhere,
-- while how long a teacher takes to answer is published nowhere at all.
--
-- This platform can publish both, because the review loop means somebody other than the
-- seller leaves a row behind. What follows is only what survives that test. An earlier draft
-- also showed "approved first time", and it is cut: the mentor writes the decision, so it is
-- the subject's own claim about themselves wearing a statistic's clothes.
--
-- ---------------------------------------------------------------------------
-- Why these are views, and why they run with the owner's rights
-- ---------------------------------------------------------------------------
-- Not cached columns on `custom_lessons`: `lessons_write_own` is `for all`, so an author can
-- update any column of their own lesson, and a reputation the subject can write is not one.
-- 0007 narrows that grant, but a view avoids the question entirely — there is no column to
-- protect, no trigger, no backfill and nothing to drift.
--
-- Both views run with definer semantics, which is deliberate and is the thing to review
-- here. `security_invoker = on` would compute each number over the rows the *caller* may
-- select — `entitlements` only shows you your own — so a public statistic would come out
-- different for every viewer, which is not a statistic. Running as the owner is only safe
-- because these views expose aggregates and nothing else: no user ids, no row-level detail,
-- and a `having` floor so a count of one cannot be read back as a fact about one person.

-- ---------------------------------------------------------------------------
-- lesson_stats — how many people this course actually reached
-- ---------------------------------------------------------------------------
-- Two different numbers wearing one name would be dishonest, so they stay separate.
--
--   `buyers`  comes from `entitlements`, which only the Stripe webhook writes. Nothing on
--             the client can forge it. It is zero for a free course, by definition.
--   `starters` counts accounts that have an assignment XP row for this lesson. Those are
--             minted in the browser — `0002` says so out loud — so this is an upper bound
--             and the interface must never call it an achievement.

create or replace view lesson_stats as
select
  l.id as lesson_id,
  (select count(*) from entitlements e where e.lesson_id = l.id) as buyers,
  (select count(distinct x.user_id) from xp_ledger x where x.kind = 'assignment' and x.ref_id = l.id::text) as starters
from custom_lessons l
where l.published;

-- ---------------------------------------------------------------------------
-- mentor_reputation — how long this person takes to read your work
-- ---------------------------------------------------------------------------
-- The median, not the mean: one project reviewed after a fortnight away drags an average
-- somewhere it will stay for months, and punishing a good mentor for taking a week off once
-- is exactly the kind of number that makes people stop trusting the number.
--
-- Ninety days, not lifetime, for the same reason in the other direction — a fast first month
-- should not carry somebody through a slow year, and a bad quarter has to be recoverable.
--
-- The floor of five is the honesty rule. Below it there is no row at all, so the interface
-- shows "new" rather than a percentage drawn from two data points. A blank where other cards
-- have numbers reads as bad, and that is a penalty aimed squarely at the newest mentors.
--
-- `reviewed_at > submitted_at` guards a negative interval. Until the fix in `api/projects.ts`
-- that shipped alongside this migration, `submitted_at` was rewritten on every save, so rows
-- created before it can be reviewed earlier than they were submitted.

create or replace view mentor_reputation as
select
  p.reviewer_id as mentor_id,
  count(*) as reviews,
  percentile_cont(0.5) within group (
    order by extract(epoch from (p.reviewed_at - p.submitted_at)) / 3600.0
  ) as median_review_hours
from projects p
where p.reviewer_id is not null
  and p.submitted_at is not null
  and p.reviewed_at is not null
  and p.reviewed_at > p.submitted_at
  and p.reviewed_at > now() - interval '90 days'
group by p.reviewer_id
having count(*) >= 5;

grant select on lesson_stats to authenticated;
grant select on mentor_reputation to authenticated;

-- ---------------------------------------------------------------------------
-- student_profiles.learning_path — the advisor's suggestion, kept
-- ---------------------------------------------------------------------------
-- An ordered list of lesson ids, and `text[]` rather than jsonb on purpose. `progress.ts`
-- syncs by diffing two states and its operations are grow-only inserts or monotonic writes,
-- which is what makes replay safe and two devices order-independent. An array compares with
-- a join, exactly as `enrolled_course_ids` already does; a jsonb document compares with
-- `!==`, which is never equal for an object literal — every sync would emit a profile
-- operation forever.
--
-- Ceiling, stated: a path is last-writer-wins, like the enrolment list beside it. Two tabs
-- reordering the same path at the same moment lose one of the orders. For a suggestion a
-- person can regenerate in one click that is the right trade; it would not be for progress.

alter table student_profiles add column if not exists learning_path text[] not null default '{}';

-- ========================================================================================
-- 0010_self_declared_mentors.sql
-- ========================================================================================

-- Three `is_mentor()` uses and one column grant that 0007 did not reach.
--
-- 0007 established the rule: since 0006, `is_mentor()` is a self-declared capability and
-- grants no authority over anybody else's row. These still treated it as authority.

-- ---------------------------------------------------------------------------
-- project_feedback: nobody writes a review from a browser
-- ---------------------------------------------------------------------------
-- `feedback_write_mentor` let any account that flipped itself to mentor insert a review, with
-- any decision, on any project, and feedback has no delete. `api/projects.ts` has written
-- feedback with the service role since 0005, so the browser needs no insert right at all.
drop policy if exists feedback_write_mentor on project_feedback;

-- ---------------------------------------------------------------------------
-- projects: a mentor sees the queue, not the drafts
-- ---------------------------------------------------------------------------
-- Drafts are unfinished work nobody has handed in. Reviewing needs submitted work and its
-- history, never a draft.
drop policy if exists projects_read on projects;
create policy projects_read on projects for select to authenticated
  using (author_id = auth.uid() or status = 'approved' or (is_mentor() and status <> 'draft') or is_admin());

-- ---------------------------------------------------------------------------
-- custom_lessons: price is gated like `published`
-- ---------------------------------------------------------------------------
-- 0007 kept `price_cents` writable, so an author could publish a lesson free through the API
-- and then price it directly — a priced lesson in the storefront with no Stripe account
-- behind it. `api/lessons.ts` saves with the service role and checks Stripe first.
revoke update on custom_lessons from authenticated;
grant update (title, summary, material_path, material_name, material_mime, material_size, updated_at)
  on custom_lessons to authenticated;

-- ========================================================================================
-- 0011_disputes.sql
-- ========================================================================================

-- Chargebacks: two more things an order can be.
--
-- 0001 gave an order four states, and one of them is about money going back: `refunded`, the
-- platform returning it. A chargeback is the buyer's bank taking it back without asking, and
-- until now the webhook did not listen for one — the bank returned the money and the student
-- kept the lesson as well. `api/webhook.ts` now withdraws access when a dispute opens and
-- decides what happens when it closes, and the order needs two words to say which:
--
--   disputed      the bank is contesting the payment. Access is withdrawn until it decides.
--   charged_back  the dispute closed against the sale. The money is gone, the lesson stays shut.
--
-- A dispute that closes in the sale's favour needs no word of its own: the order goes back to
-- `paid`, which is what it is again.
--
-- `add value` rather than recreating the type, because every row in `orders` holds it, and
-- `if not exists` so the file can be run twice like the others. Postgres will not let a value
-- added here be used in the same transaction; nothing below uses one.

alter type order_status add value if not exists 'disputed';
alter type order_status add value if not exists 'charged_back';

-- ---------------------------------------------------------------------------
-- orders: refunds and disputes find their order by payment intent
-- ---------------------------------------------------------------------------
-- A charge and a dispute both name the payment intent and never the Checkout Session, so that
-- is the column every refund and every dispute looks its order up by. Without an index each
-- of those is a scan of every sale the platform has ever made.

create index if not exists orders_payment_intent on orders (stripe_payment_intent);

-- ========================================================================================
-- 0012_ai_usage.sql
-- ========================================================================================

-- A daily allowance for the AI mentor, counted per account.
--
-- `api/mentor.ts` asks who is calling and then spends a provider key for them. That closed the
-- anonymous hole and left the ordinary one: registration is open, so an account costs nothing,
-- and a signed-in loop can run the bill up as fast as the provider will answer. `MAX_TOKENS`
-- and the input cap bound one call, not the total. Something has to count, and it has to count
-- in the database — a Vercel function keeps no memory between invocations, so a counter held
-- there would reset on every cold start and differ across every instance.
--
-- The count lives in one row per account per UTC day, and the route spends one unit before it
-- calls the provider. Over the line, the route does not call it at all and the client answers
-- from its built-in knowledge base instead, so a student who has used their day still gets help.
--
-- ---------------------------------------------------------------------------
-- Why a function, and why it runs with the owner's rights
-- ---------------------------------------------------------------------------
-- "Read the count, compare, write the count" is three steps, and two requests arriving
-- together both read 39 and both pass. The only safe shape is one statement that increments
-- *and* checks — an insert that, on conflict, updates only while the count is under the limit.
-- That statement lives in `consume_ai_quota`.
--
-- It is `security definer` because the table below deliberately lets nobody write it directly:
-- a row an account can update is a counter an account can reset. The function is the single
-- door in, and it takes the account from `auth.uid()` rather than from an argument, so a caller
-- can spend only their own allowance — there is no user id to pass, and so none to forge.
-- `set search_path = ''` and fully qualified names are Supabase's rule for definer functions:
-- with a search path an attacker can write to, a definer function can be made to resolve a
-- name to something else.
--
-- The limit is an argument rather than a constant so it can be tuned from the deployment's
-- environment without a migration. A caller who invokes this directly with a small limit can
-- only use up their own day faster; the route is what passes the real number.

-- ---------------------------------------------------------------------------
-- ai_usage
-- ---------------------------------------------------------------------------
-- UTC, not the student's local midnight: one boundary for everyone, and the same one the
-- function uses, so the row and the reset can never disagree. Old days are history and cost
-- a few bytes each; delete them whenever, nothing reads any day but today's.

create table if not exists ai_usage (
  user_id uuid not null references profiles (id) on delete cascade,
  day     date not null,
  used    integer not null default 0 check (used >= 0),
  primary key (user_id, day)
);

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
-- You can see your own count and nothing else. There is no insert, update or delete policy, and
-- the grants are revoked as well as the policies withheld: RLS is the lock, the revoke is the
-- second lock, and `consume_ai_quota` is the only key.

drop policy if exists ai_usage_read_own on ai_usage;

alter table ai_usage enable row level security;

create policy ai_usage_read_own on ai_usage for select to authenticated
  using (user_id = auth.uid());

revoke insert, update, delete on ai_usage from anon, authenticated;

-- ---------------------------------------------------------------------------
-- consume_ai_quota — spend one unit if there is one left
-- ---------------------------------------------------------------------------
-- True: a unit was spent, go ahead. False: the day is used up, or there is nobody to charge.
--
-- The first call of the day inserts a row with 1. Every later call collides with it and goes to
-- `do update`, whose `where` is the whole limit: when the count has already reached it the
-- update is skipped, no row comes back from `returning`, and `after_count` stays null. A refused
-- call changes nothing, so hammering a spent account does not push the count anywhere.
--
-- `daily_limit < 1` refuses outright. Without that, the insert branch would grant the first
-- call of the day whatever the limit said, and a limit of zero would mean one.

create or replace function public.consume_ai_quota(daily_limit integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller      uuid := auth.uid();
  after_count integer;
begin
  if caller is null or daily_limit is null or daily_limit < 1 then
    return false;
  end if;

  insert into public.ai_usage as u (user_id, day, used)
  values (caller, (now() at time zone 'utc')::date, 1)
  on conflict (user_id, day) do update
    set used = u.used + 1
    where u.used < daily_limit
  returning u.used into after_count;

  return after_count is not null;
end $$;

-- Signed-in accounts only. Postgres grants execute on a new function to everyone by default, and
-- Supabase additionally grants it to `anon` on its own, so both are revoked by name — dropping
-- `public` alone would leave the anonymous role able to call it.
revoke all on function public.consume_ai_quota(integer) from public, anon;
grant execute on function public.consume_ai_quota(integer) to authenticated;

-- ========================================================================================
-- 0013_lesson_submissions.sql
-- ========================================================================================

-- Hand-ins to mentor-written lessons, and the review of them, on the server.
--
-- `lesson_submissions` has existed since 0001 and nothing read or wrote it. The answers a
-- student gave to a mentor's lesson, and the mentor's verdict on them, lived in the student's
-- browser — so the author only ever saw what was handed in on the machine they were reviewing
-- from, which in practice means never. 0003 fixed the same thing for projects. This is the
-- other half of the review loop the product is built on.
--
-- `api/lesson-content.ts` now reads and writes this table: GET lists what the caller may see,
-- POST hands answers in and grades them against the key, PATCH is the author's decision.
--
-- It builds on 0001 (the table) and 0002 (the ledger), and is safe to run twice.

-- ---------------------------------------------------------------------------
-- submission_status: the author can send answers back
-- ---------------------------------------------------------------------------
-- 0001 gave a hand-in two states, waiting and reviewed, so a review could only ever close it.
-- Projects have always had a third — changes requested, answer again — and the README already
-- describes lessons travelling the same loop. `needs_changes` is that state.
--
-- `add value`, as 0011 does, because every row holds the type. Postgres will not let a value
-- added here be used in the same transaction, and nothing below uses it: the only code that
-- writes it is the route, after this has committed.

alter type submission_status add value if not exists 'needs_changes';

-- The student's own hand-ins, for the pull on sign-in. The author's side already has an index:
-- `unique (lesson_id, student_id)` leads with the lesson.
create index if not exists lesson_submissions_by_student on lesson_submissions (student_id);

-- ---------------------------------------------------------------------------
-- lesson_submissions: the browser reads, the route writes
-- ---------------------------------------------------------------------------
-- 0005 split the writes by column — answers for the student, grading for the author — and
-- left two holes that column grants cannot reach, because both parties are the one role
-- `authenticated`:
--
--   `submissions_insert_own` let a lesson's author hand in answers to their own free lesson,
--   and `submissions_grade` then let them grade it. With XP paid on approval, that is a
--   mentor approving themselves, one click after making themselves a mentor (0006).
--
--   `submissions_grade` let the author rewrite `quiz_score` — the platform's mark, computed
--   from a key — and rewrite `feedback` and `awarded_xp` after the student had read them. A
--   review is a record of what somebody said; the project loop is append-only for that reason.
--   And `awarded_xp` that the ledger does not agree with is a number on screen nobody was paid.
--
-- What it did get right: it is `owns_lesson()`, not `is_mentor()`, so the self-declared mentor
-- hole 0007 and 0010 closed for projects was never open here. Nobody could grade a lesson they
-- did not write.
--
-- Every write to this row now mixes columns two parties own with a judgement neither may make
-- alone. Handing in sets the answers *and* the score, and the score needs `custom_tasks`'
-- answer key, which a student may not read. Settling a quiz-only lesson sets the status *and*
-- pays XP. Reviewing sets the verdict *and* pays XP. So the browser loses its write rights here
-- entirely, as it did for project reviews in 0005 and for review feedback in 0010, and
-- `api/lesson-content.ts` writes with the service role after its own checks: access (paid →
-- entitlement, free → published, never your own lesson), and authorship for the decision.
-- Reads stay as they were — `submissions_read`: your own, the ones on lessons you wrote, admin.

drop policy if exists submissions_insert_own on lesson_submissions;
drop policy if exists submissions_grade on lesson_submissions;

-- The policies are gone and the grants go too: RLS is the lock, the revoke is the second lock.
-- Revoking at the table level also revokes the matching column privileges, so this takes
-- 0005's column grants with it.
revoke insert, update, delete on lesson_submissions from anon, authenticated;

-- ---------------------------------------------------------------------------
-- xp_ledger: assignment XP is paid by the route that decided it
-- ---------------------------------------------------------------------------
-- 0002 let a learner insert their own `assignment` rows, because a quiz-only lesson was marked
-- in the student's own browser and that browser paid it. Any account could therefore post
--
--   supabase.from('xp_ledger').insert({ user_id: me, kind: 'assignment', amount: 100000, … })
--
-- and, with any `ref_id`, add itself to the `starters` count that `lesson_stats` (0009) shows
-- on somebody's course — a number in the storefront any visitor could push up.
--
-- Assignment XP is now always a decision somebody else made about you: the server marking your
-- answers against a key you cannot read, or the author approving them. That puts it with
-- `approval` and `competition`, which 0002 already kept out of the browser for that reason.
-- The route pays it with the service role, and `xp_ledger_paid_once` still pays it once per
-- lesson, which is what keeps a resubmission from paying twice.
--
-- `src/lib/progress.ts` holds this list as `BROWSER_XP_KINDS`, so the client stops sending what
-- this refuses rather than failing a whole batch on it.

drop policy if exists xp_ledger_insert_own on xp_ledger;
create policy xp_ledger_insert_own on xp_ledger for insert to authenticated
  with check (user_id = auth.uid() and kind in ('lesson', 'challenge', 'achievement', 'submission'));

commit;

-- Every row below should say true.
select 'accounts and lessons (0001)' as piece, to_regclass('public.profiles') is not null and to_regclass('public.custom_lessons') is not null as ok
union all select 'progress sync (0002)', to_regclass('public.xp_ledger') is not null
union all select 'projects and reviews (0003)', to_regclass('public.projects') is not null
union all select 'notifications (0004)', to_regclass('public.notifications') is not null
union all select 'demand board (0008)', to_regclass('public.course_requests') is not null
union all select 'chargebacks (0011)', exists (select 1 from pg_enum e join pg_type t on t.oid = e.enumtypid where t.typname = 'order_status' and e.enumlabel = 'charged_back')
union all select 'AI mentor daily limit (0012)', to_regprocedure('public.consume_ai_quota(integer)') is not null
union all select 'lesson hand-ins sent back (0013)', exists (select 1 from pg_enum e join pg_type t on t.oid = e.enumtypid where t.typname = 'submission_status' and e.enumlabel = 'needs_changes');
